using System.Collections.Generic;
using LoveGame.Core;
using UnityEngine;

namespace LoveGame.Core
{
    /// <summary>
    /// Central material cache. All runtime-created visuals share materials from here to avoid
    /// duplicate-material draw-call explosions. Custom shaders live in Resources/Shaders so they
    /// are always included in builds; standard shaders resolve via Resources/Materials assets
    /// generated by the editor setup wizard (with Shader.Find fallback).
    /// </summary>
    public static class MaterialLibrary
    {
        static readonly Dictionary<string, Material> Cache = new Dictionary<string, Material>();
        static Material _lit, _particle, _water, _vertexColor, _skybox;

        public const string ShaderVertexColor = "LoveGame/TerrainVertexColor";
        public const string ShaderWater = "LoveGame/StylizedWater";
        public const string ShaderEmissive = "LoveGame/EmissiveUnlit";
        public const string ShaderSkybox = "LoveGame/GradientSkybox";

        // Custom shaders apply distance fog manually - the world system keeps these globals in sync
        // with RenderSettings so custom and standard materials fog identically.
        public static void SetGlobalFog(Color color, float density, float startDistance)
        {
            Shader.SetGlobalColor("_LGFogColor", color);
            Shader.SetGlobalFloat("_LGFogDensity", density);
            Shader.SetGlobalFloat("_LGFogStart", startDistance);
            Shader.SetGlobalVector("_LGSunDir", Shader.GetGlobalVector("_LGSunDir"));
            Shader.SetGlobalFloat("_LGDayFactor", Shader.GetGlobalFloat("_LGDayFactor"));
        }

        public static void SetSun(Vector3 direction, float dayFactor)
        {
            Shader.SetGlobalVector("_LGSunDir", new Vector4(direction.x, direction.y, direction.z, 0f));
            Shader.SetGlobalFloat("_LGDayFactor", dayFactor);
        }

        static Shader FindShader(string name)
        {
            var s = Shader.Find(name);
            if (s == null) Log.Warn("Materials", $"shader '{name}' missing (pink fallback)");
            return s;
        }

        /// <summary>Standard lit surface material (URP Lit in URP projects, Built-in Standard otherwise).</summary>
        public static Material Lit => _lit ?? (_lit = LoadOrFind("Materials/Lit", "Universal Render Pipeline/Lit", "Standard"));

        /// <summary>Unlit transparent white particle material.</summary>
        public static Material Particle => _particle ?? (_particle = LoadOrFind("Materials/Particle", "Universal Render Pipeline/Particles/Unlit", "Particles/Standard Unlit"));

        public static Material Water => _water ?? (_water = new Material(FindShader(ShaderWater)) { renderQueue = 3000 });

        public static Material VertexColor => _vertexColor ?? (_vertexColor = new Material(FindShader(ShaderVertexColor)));

        public static Material Skybox => _skybox ?? (_skybox = new Material(FindShader(ShaderSkybox)));

        static Material LoadOrFind(string resourcesPath, string urpShader, string fallbackShader)
        {
            var loaded = Resources.Load<Material>(resourcesPath);
            if (loaded != null) return loaded;
            var shader = Shader.Find(urpShader) ?? Shader.Find(fallbackShader);
            if (shader == null)
            {
                Log.Error("Materials", $"no lit shader available ({urpShader} / {fallbackShader})");
                shader = Shader.Find("Hidden/InternalErrorShader");
            }
            return new Material(shader);
        }

        /// <summary>Cached colored variant of a base material (tint copy - cheap, shared per color).</summary>
        public static Material Tinted(Material baseMaterial, Color color, string cacheKey)
        {
            var key = baseMaterial.name + "|" + cacheKey;
            if (Cache.TryGetValue(key, out var m)) return m;
            m = new Material(baseMaterial) { color = color };
            m.name = key;
            Cache[key] = m;
            return m;
        }

        /// <summary>Emissive glow material (bloom-friendly) for crystals, beacons, neon.</summary>
        public static Material Emissive(Color color, float intensity = 1.6f)
        {
            var key = $"emissive|{color.r:F3},{color.g:F3},{color.b:F3},{intensity:F2}";
            if (Cache.TryGetValue(key, out var m)) return m;
            m = new Material(FindShader(ShaderEmissive));
            m.SetColor("_Color", color * intensity);
            Cache[key] = m;
            return m;
        }

        /// <summary>Transparent water body material with the region's water color.</summary>
        public static Material WaterColored(Color color)
        {
            var key = $"water|{color.r:F3},{color.g:F3},{color.b:F3}";
            if (Cache.TryGetValue(key, out var m)) return m;
            m = new Material(Water);
            m.SetColor("_Color", color);
            Cache[key] = m;
            return m;
        }

        /// <summary>Vertex-colored terrain material (biome blend painted into mesh vertices).</summary>
        public static Material Terrain => VertexColor;

        public static void DisposeAll()
        {
            Cache.Clear();
            _lit = null; _particle = null; _water = null; _vertexColor = null; _skybox = null;
        }
    }
}
